import type { Spell } from "./types";

export const spells: Spell[] = [
  {"id":  0, "level": 1, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id":  1, "level": 1, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id":  2, "level": 1, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id":  3, "level": 1, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id":  4, "level": 2, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id":  5, "level": 2, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id":  6, "level": 2, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id":  7, "level": 2, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id":  8, "level": 3, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id":  9, "level": 3, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 10, "level": 3, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 11, "level": 3, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 12, "level": 4, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 13, "level": 4, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 14, "level": 4, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 15, "level": 4, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 16, "level": 5, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 17, "level": 5, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 18, "level": 5, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 19, "level": 5, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 20, "level": 6, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 21, "level": 6, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 22, "level": 6, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 23, "level": 6, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 24, "level": 7, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 25, "level": 7, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 26, "level": 7, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 27, "level": 7, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 28, "level": 8, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 29, "level": 8, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 30, "level": 8, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 31, "level": 8, "name": "Temp Spell 4", "description": "Temporary description 4."},
  {"id": 32, "level": 9, "name": "Temp Spell 1", "description": "Temporary description 1."},
  {"id": 33, "level": 9, "name": "Temp Spell 2", "description": "Temporary description 2."},
  {"id": 34, "level": 9, "name": "Temp Spell 3", "description": "Temporary description 3."},
  {"id": 35, "level": 9, "name": "Temp Spell 4", "description": "Temporary description 4."}
]